import React, { useState } from 'react'

function Database() {
    const[interns, SetInterns] = useState([
        {
            name:"Okafor Ephraim",
            LearningPath:"Frontend",
            grade:"80",
            id:"0",
            email:"ephraim@gmail.com",
            img:require("./assets/imgs/01.jpeg")
        },
        {
            name:"Nneoma Jane",
            LearningPath:"Frontend",
            grade:"65",
            id:"1",
            email:"nneoma@gmail.com",
            img:require("./assets/imgs/02.webp")
        },
        {
            name:"Eze Austin",
            LearningPath:"Frontend",
            grade:"97",
            id:"2",
            email:"eze@gmail.com",
            img:require("./assets/imgs/03.webp")
        }
        ,
        {
            name:"Chinedu Mary",
            LearningPath:"Frontend",
            grade:"65",
            id:"3",
            email:"mary@gmail.com",
            img:require("./assets/imgs/04.jpeg")
        }
        ,
        {
            name:"Michael John",
            LearningPath:"Frontend",
            grade:"72",
            id:"4",
            email:"michael@yahoo.com",
            img:require("./assets/imgs/05.webp")
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        ,
        {
            name:"",
            LearningPath:"",
            grade:"",
            id:"",
            email:""
        }
        
        
        
    ]);
  return (
    <div>database</div>
  )
}

export default Database